### ISSUE TITLE
End of Game check

### ISSUE THREAD

**Issue by twiliuh** [megan-ou/Mahjong_Bouchard_Cabral_Harrison_Ou#1]
When the human player wins the game, the game can recognize they've won by allowing them to accept a tile into the "win" space in their hand, but something is going wrong in recognizing that this is the end of the game because continued gameplay is still possible (can continue discarding/drawing tiles).

**Comment by megan-ou** [comment]
End of game check now works using a permutation sort to find the ideal order of tiles to win the game.
